// global using DOL.AI.Brain;
// global using DOL.Config;
global using DOL.Database;
// global using DOL.Database.Attributes;
// global using DOL.Database.Connection;
// global using DOL.Events;
global using DOL.GS;
// global using DOL.GS.Behaviour;
// global using DOL.GS.DatabaseUpdate;
// global using DOL.GS.Effects;
// global using DOL.GS.Housing;
// global using DOL.GS.Keeps;
global using DOL.GS.PacketHandler;
// global using DOL.GS.PacketHandler.Client.v168;
// global using DOL.GS.PlayerClass;
// global using DOL.GS.PlayerTitles;
// global using DOL.GS.Quests;
// global using DOL.GS.ServerProperties;
// global using DOL.GS.ServerRules;
global using DOL.GS.Spells;
// global using DOL.GS.Styles;
global using DOL.Language;
// global using DOL.Mail;
// global using DOL.Network;
global using log4net;
// global using log4net.Config;
// global using log4net.Core;
global using System;
// global using System.Collections.Concurrent;
global using System.Collections.Generic;
// global using System.Diagnostics;
// global using System.IO;
global using System.Linq;
// global using System.Net;
// global using System.Net.Http;
// global using System.Net.Sockets;
// global using System.Reflection;
global using System.Text;
// global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Threading.Tasks;
// global using System.Timers;
// global using JNogueira.Discord.Webhook.Client;